# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sqlflow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sqlflow.proto',
  package='sqlflowserver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rsqlflow.proto\x12\rsqlflowserver\x1a\x19google/protobuf/any.proto\"\x19\n\nRunRequest\x12\x0b\n\x03sql\x18\x01 \x01(\t\"q\n\x0bRunResponse\x12+\n\x08messages\x18\x01 \x01(\x0b\x32\x17.sqlflowserver.MessagesH\x00\x12)\n\x07\x63olumns\x18\x02 \x01(\x0b\x32\x16.sqlflowserver.ColumnsH\x00\x42\n\n\x08response\"\x1c\n\x08Messages\x12\x10\n\x08messages\x18\x01 \x03(\t\"\xbc\x01\n\x07\x43olumns\x12\x34\n\x07\x63olumns\x18\x01 \x03(\x0b\x32#.sqlflowserver.Columns.ColumnsEntry\x1aM\n\x0c\x43olumnsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.sqlflowserver.Columns.Column:\x02\x38\x01\x1a,\n\x06\x43olumn\x12\"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any2I\n\x07SQLFlow\x12>\n\x03Run\x12\x19.sqlflowserver.RunRequest\x1a\x1a.sqlflowserver.RunResponse0\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_RUNREQUEST = _descriptor.Descriptor(
  name='RunRequest',
  full_name='sqlflowserver.RunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sql', full_name='sqlflowserver.RunRequest.sql', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=84,
)


_RUNRESPONSE = _descriptor.Descriptor(
  name='RunResponse',
  full_name='sqlflowserver.RunResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='sqlflowserver.RunResponse.messages', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='columns', full_name='sqlflowserver.RunResponse.columns', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='sqlflowserver.RunResponse.response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=86,
  serialized_end=199,
)


_MESSAGES = _descriptor.Descriptor(
  name='Messages',
  full_name='sqlflowserver.Messages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='sqlflowserver.Messages.messages', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=229,
)


_COLUMNS_COLUMNSENTRY = _descriptor.Descriptor(
  name='ColumnsEntry',
  full_name='sqlflowserver.Columns.ColumnsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='sqlflowserver.Columns.ColumnsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='sqlflowserver.Columns.ColumnsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=374,
)

_COLUMNS_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='sqlflowserver.Columns.Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='sqlflowserver.Columns.Column.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=420,
)

_COLUMNS = _descriptor.Descriptor(
  name='Columns',
  full_name='sqlflowserver.Columns',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columns', full_name='sqlflowserver.Columns.columns', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COLUMNS_COLUMNSENTRY, _COLUMNS_COLUMN, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=420,
)

_RUNRESPONSE.fields_by_name['messages'].message_type = _MESSAGES
_RUNRESPONSE.fields_by_name['columns'].message_type = _COLUMNS
_RUNRESPONSE.oneofs_by_name['response'].fields.append(
  _RUNRESPONSE.fields_by_name['messages'])
_RUNRESPONSE.fields_by_name['messages'].containing_oneof = _RUNRESPONSE.oneofs_by_name['response']
_RUNRESPONSE.oneofs_by_name['response'].fields.append(
  _RUNRESPONSE.fields_by_name['columns'])
_RUNRESPONSE.fields_by_name['columns'].containing_oneof = _RUNRESPONSE.oneofs_by_name['response']
_COLUMNS_COLUMNSENTRY.fields_by_name['value'].message_type = _COLUMNS_COLUMN
_COLUMNS_COLUMNSENTRY.containing_type = _COLUMNS
_COLUMNS_COLUMN.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_COLUMNS_COLUMN.containing_type = _COLUMNS
_COLUMNS.fields_by_name['columns'].message_type = _COLUMNS_COLUMNSENTRY
DESCRIPTOR.message_types_by_name['RunRequest'] = _RUNREQUEST
DESCRIPTOR.message_types_by_name['RunResponse'] = _RUNRESPONSE
DESCRIPTOR.message_types_by_name['Messages'] = _MESSAGES
DESCRIPTOR.message_types_by_name['Columns'] = _COLUMNS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunRequest = _reflection.GeneratedProtocolMessageType('RunRequest', (_message.Message,), dict(
  DESCRIPTOR = _RUNREQUEST,
  __module__ = 'sqlflow_pb2'
  # @@protoc_insertion_point(class_scope:sqlflowserver.RunRequest)
  ))
_sym_db.RegisterMessage(RunRequest)

RunResponse = _reflection.GeneratedProtocolMessageType('RunResponse', (_message.Message,), dict(
  DESCRIPTOR = _RUNRESPONSE,
  __module__ = 'sqlflow_pb2'
  # @@protoc_insertion_point(class_scope:sqlflowserver.RunResponse)
  ))
_sym_db.RegisterMessage(RunResponse)

Messages = _reflection.GeneratedProtocolMessageType('Messages', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGES,
  __module__ = 'sqlflow_pb2'
  # @@protoc_insertion_point(class_scope:sqlflowserver.Messages)
  ))
_sym_db.RegisterMessage(Messages)

Columns = _reflection.GeneratedProtocolMessageType('Columns', (_message.Message,), dict(

  ColumnsEntry = _reflection.GeneratedProtocolMessageType('ColumnsEntry', (_message.Message,), dict(
    DESCRIPTOR = _COLUMNS_COLUMNSENTRY,
    __module__ = 'sqlflow_pb2'
    # @@protoc_insertion_point(class_scope:sqlflowserver.Columns.ColumnsEntry)
    ))
  ,

  Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), dict(
    DESCRIPTOR = _COLUMNS_COLUMN,
    __module__ = 'sqlflow_pb2'
    # @@protoc_insertion_point(class_scope:sqlflowserver.Columns.Column)
    ))
  ,
  DESCRIPTOR = _COLUMNS,
  __module__ = 'sqlflow_pb2'
  # @@protoc_insertion_point(class_scope:sqlflowserver.Columns)
  ))
_sym_db.RegisterMessage(Columns)
_sym_db.RegisterMessage(Columns.ColumnsEntry)
_sym_db.RegisterMessage(Columns.Column)


_COLUMNS_COLUMNSENTRY._options = None

_SQLFLOW = _descriptor.ServiceDescriptor(
  name='SQLFlow',
  full_name='sqlflowserver.SQLFlow',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=422,
  serialized_end=495,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='sqlflowserver.SQLFlow.Run',
    index=0,
    containing_service=None,
    input_type=_RUNREQUEST,
    output_type=_RUNRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SQLFLOW)

DESCRIPTOR.services_by_name['SQLFlow'] = _SQLFLOW

# @@protoc_insertion_point(module_scope)
